POST http://localhost:8000/products HTTP/1.1
Content-Type: application/json

{
    "name": "my product 4",
    "price": 208.54
}

###

GET http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzUyOTUwMTcsInN1YiI6ImIzMDUyOGVhLTliZDgtNDU5NS1iM2JhLWU1MDlmNmJjYjM4MiJ9.19eH60BbhF-WM8tLQHnHl3T33ydz2ZLzYuNEhWGTLkU

###

GET http://localhost:8000/products/0ce11648-010e-4f68-891c-8d794886ea72 HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:8000/products/0ce11648-010e-4f68-891c-8d794886ea72 HTTP/1.1
Content-Type: application/json

{
    "name": "my product updated",
    "price": 200
}

###

DELETE http://localhost:8000/products/0ce11648-010e-4f68-891c-8d794886ea72 HTTP/1.1
Content-Type: application/json