POST http://localhost:8000/users HTTP/1.1
Content-Type: application/json

{
    "name": "Edio",
    "email": "ediogama@hotmail.com",
    "password": "123456"
}

###

POST http://localhost:8000/users/generate_token HTTP/1.1
Content-Type: application/json

{
    "email": "ediogama@hotmail.com",
    "password": "123456"
}